added a little extra documentation
jeveleth/dolley-madison pull request #6
Opened 2016-12-22 14:26 UTC by titaniumbones

just makes it a little easier for the ignorant like me!

2016-12-22 16:01 UTC, jeveleth requested changes
Looks good. Added a couple of comments.

2016-12-22 16:01 UTC, jeveleth commented on README.md
> +If you have a git username and ouath key, you can fork the repos yourself. Running this script will create ~1670 new repositoriies in your account, so you may want to create a special account just fo
"repositoriies" should be "repositories"

2016-12-22 16:01 UTC, jeveleth commented on README.md
> +(Obviously you can use also  some other mechanism to set the relevnat environment variables.)
"relevnat" should be "relevant"

2016-12-23 06:38 UTC, jeveleth approved these changes

2016-12-23 15:59 UTC, titaniumbones commented
The PR is still open but I think all changes have been approved. I haven't used change requests much so tell me if I'm doing something wrong...

2016-12-24 02:25 UTC, jeveleth commented
Looks good. Thanks for the documentation!

2016-12-24 02:25 UTC, merged